name: Build & Auto-Release Wormhole

on:
  push:
    branches: [ "main", "master" ]
    paths-ignore: [ "README.md" ]
  pull_request:
    branches: [ "main", "master" ]
    paths-ignore: [ "README.md" ]

jobs:
  build:
    name: Build for ${{ matrix.goos }}/${{ matrix.goarch }}
    runs-on: ubuntu-latest

    # For ncipollo action to create releases
    permissions:
          contents: write

    strategy:
      matrix:
        # OS and Architecture combos
        include:
          - goos: linux
            goarch: amd64
            output: wormhole-linux-amd64
          - goos: windows
            goarch: amd64
            output: wormhole-windows-amd64.exe
          - goos: darwin
            goarch: amd64
            output: wormhole-mac-intel
          - goos: darwin
            goarch: arm64
            output: wormhole-mac-silicon

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26.1'

    - name: Download Dependencies
      run: go mod download

    - name: Build Binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      # Compiles the code and places it in a temporary 'dist' folder
      run: go build -o dist/${{ matrix.output }} main.go

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: dist/${{ matrix.output }}
        # Custom dynamic versioning
        tag: v1.${{github.run_number}}.${{github.run_attempt}}
        token: ${{ secrets.GITHUB_TOKEN }}
        
        # For our matrix builds:
        allowUpdates: true 
        omitBodyDuringUpdate: true
        generateReleaseNotes: true
